### ISSUE TITLE
method to easily change the templates directory

### ISSUE THREAD

**Issue by andy5995** [dafky2000/simplectemplate#14]
https://github.com/dafky2000/simplectemplate/blob/e912832ebe15b48a72b13238c3e07c2f3d00e04d/src/main.c#L35

I used this method for the code you generously donated
```
#define TEMPLATE_INDEX_PATH "../templates/index.html"
#define TEMPLATE_ARTICLE_PATH "../templates/article.html"
#define TEMPLATE_ARTLNK_PATH "../templates/article_link.html"
```

The other two options for implementing a way to specify the template directory (if that's something you want) is a config file or passing it on the command line.

**Comment by dafky2000** [comment]
Oh! main.c is primarily just a showcase, not really meant to be run by "users". I will populate it with tests and usage examples as the library builds.
