### ISSUE TITLE
Implement unit testing

### ISSUE THREAD

**Issue by dafky2000** [dafky2000/simplectemplate#2]
Select framework and implement a suitable unit test framework.

**Comment by dafky2000** [comment]
I believe this is the last issue required for a v0.0.1 tag :)

**Comment by dafky2000** [comment]
I've used google-test in the past and I don't mind the unit tests in C++
https://github.com/bast/gtest-demo

**Comment by apfohl** [comment]
Some time ago I wrote a neat little unit testing framework in C for C. It would be a pleasure to help you by integrating it into your project.

https://github.com/compiler-dept/speck

**Comment by dafky2000** [comment]
Simple and straight forward, I like it! Would love your help integrating speck into this project. I prefer it to be setup as as a git submodule.

Please base off of and create your pull request on the `develop` branch :)

**Comment by apfohl** [comment]
Thank you, I will do it tonight.

**Comment by apfohl** [comment]
Done, please have a look at PR #32.

**Comment by dafky2000** [comment]
Great! Now I can start adding some basic tests. :) Thanks again @apfohl!

**Comment by apfohl** [comment]
I added a first test for you.

**Comment by dafky2000** [comment]
Got all the basic unit tests added, speck is very easy to use :)
