### ISSUE TITLE
Create CONTRIBUTING.md with sane contributing guidelines

### ISSUE THREAD

**Issue by dafky2000** [dafky2000/simplectemplate#3]

**Comment by Supun94** [comment]
@dafky2000 I would like to take this issue and will send a PR

**Comment by LShun** [comment]
@Supun94 I've sent a PR, its a very basic CONTRIBUTING.md, but might as well as start there.

**Comment by dafky2000** [comment]
@lshun I would like to give @supun94 the chance to submit a pr since they were the first to comment. I'm sure we can come up with something sane between the 3 of us! :-) Your work looks like good base guidelines, thank you!

**Comment by LShun** [comment]
Alright sure, no problem with that 👍

**Comment by Supun94** [comment]
@dafky2000 Please review the PR #9 :) Sorry @LShun I haven't noticed you also trying to send a PR for this issue :/

**Comment by LShun** [comment]
@Supun94 No prob, we're all here only to help anyways, no need for any sorry. 😄

**Comment by dafky2000** [comment]
Closed via #9, #6, #12
