### ISSUE TITLE
declare functions as static

### ISSUE THREAD

**Issue by andy5995** [dafky2000/simplectemplate#46]
Looks like you have at least 2 functions in template_functions.c that could be declared as static.

The prototypes would have to be removed from the .h file.

http://www.c-programming-simple-steps.com/static-keyword-in-c.html

Let me know if you'd like me to work on this.

**Comment by dafky2000** [comment]
Please forgive my ignorance if I am wrong but I don't see the benefit or use-case in this situation. I am not opposed to it if there is a benefit and I am all ears :)

**Comment by andy5995** [comment]
Not any great benefit. Functions that don't need to be visible by main would be invisible to main. So.. about as much benefit as reducing the scope of a variable, or changing a global variable local to a single function. I couldn't speak to any specifics about how that would reduce cpu or memory overhead, but obviously it would not be significant.

**Comment by dafky2000** [comment]
Ok, that makes sense. Better to keep things scoped accurately. Go for it :)

**Comment by dafky2000** [comment]
Thank you for the contribution!!
